[profile.default]
src = "contracts"
out = "contracts/artifacts"
libs = ["node_modules"]
solc_version = "0.8.28"
evm_version = "cancun"

remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]
