/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'CrowdMembership', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CrowdMembership__factory>
getContractFactory(name: 'QueueBoost', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.QueueBoost__factory>
getContractFactory(name: 'CrowdToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CrowdToken__factory>

  getContractAt(name: 'CrowdMembership', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CrowdMembership>
getContractAt(name: 'QueueBoost', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.QueueBoost>
getContractAt(name: 'CrowdToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CrowdToken>

  deployContract(name: 'CrowdMembership', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CrowdMembership>
deployContract(name: 'QueueBoost', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QueueBoost>
deployContract(name: 'CrowdToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CrowdToken>

  deployContract(name: 'CrowdMembership', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CrowdMembership>
deployContract(name: 'QueueBoost', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QueueBoost>
deployContract(name: 'CrowdToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CrowdToken>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  