/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface QueueBoostInterface extends Interface {
    getFunction(nameOrSignature: "CREATOR_SHARE" | "PLATFORM_SHARE" | "boostPrice" | "buyBoost" | "creatorEarnings" | "crowdToken" | "owner" | "platformTreasury" | "playNext" | "playNextPrice" | "queueJumpPrice" | "renounceOwnership" | "superPriorityPrice" | "tipCreator" | "transferOwnership" | "withdrawEarnings"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BoostPurchased" | "CreatorRewarded" | "EarningsWithdrawn" | "OwnershipTransferred" | "SongPromoted"): EventFragment;

    encodeFunctionData(functionFragment: 'CREATOR_SHARE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PLATFORM_SHARE', values?: undefined): string;
encodeFunctionData(functionFragment: 'boostPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyBoost', values: [BytesLike, BytesLike, string, AddressLike]): string;
encodeFunctionData(functionFragment: 'creatorEarnings', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'crowdToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'playNext', values: [BytesLike, BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'playNextPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'queueJumpPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'superPriorityPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'tipCreator', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawEarnings', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'CREATOR_SHARE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PLATFORM_SHARE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'boostPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyBoost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creatorEarnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'crowdToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'playNext', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'playNextPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'queueJumpPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'superPriorityPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tipCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawEarnings', data: BytesLike): Result;
  }

  
    export namespace BoostPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, roomId: BytesLike, itemId: BytesLike, amount: BigNumberish, boostType: string];
      export type OutputTuple = [buyer: string, roomId: string, itemId: string, amount: bigint, boostType: string];
      export interface OutputObject {buyer: string, roomId: string, itemId: string, amount: bigint, boostType: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreatorRewardedEvent {
      export type InputTuple = [creator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [creator: string, amount: bigint];
      export interface OutputObject {creator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EarningsWithdrawnEvent {
      export type InputTuple = [creator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [creator: string, amount: bigint];
      export interface OutputObject {creator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SongPromotedEvent {
      export type InputTuple = [roomId: BytesLike, itemId: BytesLike, boostType: string];
      export type OutputTuple = [roomId: string, itemId: string, boostType: string];
      export interface OutputObject {roomId: string, itemId: string, boostType: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface QueueBoost extends BaseContract {
    
    connect(runner?: ContractRunner | null): QueueBoost;
    waitForDeployment(): Promise<this>;

    interface: QueueBoostInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CREATOR_SHARE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PLATFORM_SHARE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    boostPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buyBoost: TypedContractMethod<
      [roomId: BytesLike, itemId: BytesLike, boostType: string, creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    creatorEarnings: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    crowdToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    platformTreasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    playNext: TypedContractMethod<
      [roomId: BytesLike, itemId: BytesLike, creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    playNextPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    queueJumpPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    superPriorityPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tipCreator: TypedContractMethod<
      [creator: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawEarnings: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CREATOR_SHARE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PLATFORM_SHARE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'boostPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyBoost'): TypedContractMethod<
      [roomId: BytesLike, itemId: BytesLike, boostType: string, creator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'creatorEarnings'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'crowdToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'platformTreasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'playNext'): TypedContractMethod<
      [roomId: BytesLike, itemId: BytesLike, creator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'playNextPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'queueJumpPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'superPriorityPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tipCreator'): TypedContractMethod<
      [creator: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawEarnings'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BoostPurchased'): TypedContractEvent<BoostPurchasedEvent.InputTuple, BoostPurchasedEvent.OutputTuple, BoostPurchasedEvent.OutputObject>;
getEvent(key: 'CreatorRewarded'): TypedContractEvent<CreatorRewardedEvent.InputTuple, CreatorRewardedEvent.OutputTuple, CreatorRewardedEvent.OutputObject>;
getEvent(key: 'EarningsWithdrawn'): TypedContractEvent<EarningsWithdrawnEvent.InputTuple, EarningsWithdrawnEvent.OutputTuple, EarningsWithdrawnEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'SongPromoted'): TypedContractEvent<SongPromotedEvent.InputTuple, SongPromotedEvent.OutputTuple, SongPromotedEvent.OutputObject>;

    filters: {
      
      'BoostPurchased(address,bytes32,bytes32,uint256,string)': TypedContractEvent<BoostPurchasedEvent.InputTuple, BoostPurchasedEvent.OutputTuple, BoostPurchasedEvent.OutputObject>;
      BoostPurchased: TypedContractEvent<BoostPurchasedEvent.InputTuple, BoostPurchasedEvent.OutputTuple, BoostPurchasedEvent.OutputObject>;
    

      'CreatorRewarded(address,uint256)': TypedContractEvent<CreatorRewardedEvent.InputTuple, CreatorRewardedEvent.OutputTuple, CreatorRewardedEvent.OutputObject>;
      CreatorRewarded: TypedContractEvent<CreatorRewardedEvent.InputTuple, CreatorRewardedEvent.OutputTuple, CreatorRewardedEvent.OutputObject>;
    

      'EarningsWithdrawn(address,uint256)': TypedContractEvent<EarningsWithdrawnEvent.InputTuple, EarningsWithdrawnEvent.OutputTuple, EarningsWithdrawnEvent.OutputObject>;
      EarningsWithdrawn: TypedContractEvent<EarningsWithdrawnEvent.InputTuple, EarningsWithdrawnEvent.OutputTuple, EarningsWithdrawnEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'SongPromoted(bytes32,bytes32,string)': TypedContractEvent<SongPromotedEvent.InputTuple, SongPromotedEvent.OutputTuple, SongPromotedEvent.OutputObject>;
      SongPromoted: TypedContractEvent<SongPromotedEvent.InputTuple, SongPromotedEvent.OutputTuple, SongPromotedEvent.OutputObject>;
    
    };
  }